// Generated by gencpp from file robotico/string_msgRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICO_MESSAGE_STRING_MSGREQUEST_H
#define ROBOTICO_MESSAGE_STRING_MSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotico
{
template <class ContainerAllocator>
struct string_msgRequest_
{
  typedef string_msgRequest_<ContainerAllocator> Type;

  string_msgRequest_()
    : in()  {
    }
  string_msgRequest_(const ContainerAllocator& _alloc)
    : in(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _in_type;
  _in_type in;





  typedef boost::shared_ptr< ::robotico::string_msgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotico::string_msgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct string_msgRequest_

typedef ::robotico::string_msgRequest_<std::allocator<void> > string_msgRequest;

typedef boost::shared_ptr< ::robotico::string_msgRequest > string_msgRequestPtr;
typedef boost::shared_ptr< ::robotico::string_msgRequest const> string_msgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotico::string_msgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotico::string_msgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotico

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotico::string_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotico::string_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotico::string_msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotico::string_msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotico::string_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotico::string_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotico::string_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2718218ecd3037e7050a0e8416c50c33";
  }

  static const char* value(const ::robotico::string_msgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2718218ecd3037e7ULL;
  static const uint64_t static_value2 = 0x050a0e8416c50c33ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotico::string_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotico/string_msgRequest";
  }

  static const char* value(const ::robotico::string_msgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotico::string_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string in\n\
";
  }

  static const char* value(const ::robotico::string_msgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotico::string_msgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct string_msgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotico::string_msgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotico::string_msgRequest_<ContainerAllocator>& v)
  {
    s << indent << "in: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICO_MESSAGE_STRING_MSGREQUEST_H
